// Code generated by MockGen. DO NOT EDIT.
// Source: ./deployer/deployer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	workloads "github.com/threefoldtech/grid3-go/workloads"
	gridtypes "github.com/threefoldtech/zos/pkg/gridtypes"
)

// MockDeployerInterface is a mock of DeployerInterface interface.
type MockDeployerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeployerInterfaceMockRecorder
}

// MockDeployerInterfaceMockRecorder is the mock recorder for MockDeployerInterface.
type MockDeployerInterfaceMockRecorder struct {
	mock *MockDeployerInterface
}

// NewMockDeployerInterface creates a new mock instance.
func NewMockDeployerInterface(ctrl *gomock.Controller) *MockDeployerInterface {
	mock := &MockDeployerInterface{ctrl: ctrl}
	mock.recorder = &MockDeployerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeployerInterface) EXPECT() *MockDeployerInterfaceMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockDeployerInterface) Cancel(ctx context.Context, contractID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, contractID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockDeployerInterfaceMockRecorder) Cancel(ctx, contractID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockDeployerInterface)(nil).Cancel), ctx, contractID)
}

// Deploy mocks base method.
func (m *MockDeployerInterface) Deploy(ctx context.Context, oldDeploymentIDs map[uint32]uint64, newDeployments map[uint32]gridtypes.Deployment, newDeploymentsData map[uint32]workloads.DeploymentData, newDeploymentSolutionProvider map[uint32]*uint64) (map[uint32]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deploy", ctx, oldDeploymentIDs, newDeployments, newDeploymentsData, newDeploymentSolutionProvider)
	ret0, _ := ret[0].(map[uint32]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deploy indicates an expected call of Deploy.
func (mr *MockDeployerInterfaceMockRecorder) Deploy(ctx, oldDeploymentIDs, newDeployments, newDeploymentsData, newDeploymentSolutionProvider interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deploy", reflect.TypeOf((*MockDeployerInterface)(nil).Deploy), ctx, oldDeploymentIDs, newDeployments, newDeploymentsData, newDeploymentSolutionProvider)
}

// GetDeployments mocks base method.
func (m *MockDeployerInterface) GetDeployments(ctx context.Context, dls map[uint32]uint64) (map[uint32]gridtypes.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeployments", ctx, dls)
	ret0, _ := ret[0].(map[uint32]gridtypes.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeployments indicates an expected call of GetDeployments.
func (mr *MockDeployerInterfaceMockRecorder) GetDeployments(ctx, dls interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeployments", reflect.TypeOf((*MockDeployerInterface)(nil).GetDeployments), ctx, dls)
}
